### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by drcege** [albanie/pytorch-mcn#3]
```bash
*** SyntaxError: invalid syntax
> /home/gece/Workspace/pytorch-mcn/python/importer.py(239)extract_dag()
    238         else: import ipdb ; ipdb.set_trace()
--> 239         for output, out_ch in zip(node['outputs'], out_chs):
    240             in_ch_store[output] = out_ch

ipdb>

```

I got the above error when trying to convert [imagenet-vgg-f](http://www.vlfeat.org/matconvnet/models/imagenet-vgg-f.mat) and [imagenet-vgg-m-1024](http://www.vlfeat.org/matconvnet/models/imagenet-vgg-m-1024.mat). I have already converted them to dags using ensure_dags.m.  
( I use python3.5, and I can convert [imagenet-vgg-verydeep-16](http://www.vlfeat.org/matconvnet/models/imagenet-vgg-verydeep-16.mat) successfully )

**Comment by albanie** [comment]
Hi @drcege, I didn't port those previously due to the usage of Local Response Normalization which wasn't supported by pytorch at the time.  It looks like it has recently been added to the master branch [here]((https://github.com/pytorch/pytorch/issues/653) and will be included in the next release, so I'll take a look at adding support for those layers.

**Comment by CoderHHX** [comment]
Hi, @albanie , Thank you for your great work. I want to use vgg_m from matcovnet pretrained model. Could you please give these pretained models, I find a vgg_m implement by pytorch https://github.com/tzing/vgg-fms. How I can convert it

**Comment by albanie** [comment]
Hi @CoderHHX, sorry for the slow response.  There is a copy of vgg-m converted from the original matconvnet pretrained version here: http://www.robots.ox.ac.uk/~albanie/pytorch-models.html#mcn-pretrained-examples

Lmk if you have issues.

**Comment by CoderHHX** [comment]
@albanie Thank you so much!

**Comment by albanie** [comment]
no problem!
